/**
 * TypeScript mirror of public/data/archive.json, generated by
 * angular-web/scripts/sync-data.mjs.
 *
 * daily.json only ever describes a single day. This index lists every article
 * ever published, newest first, so search and the archive page can reach past
 * content. It carries no article body — just enough to render a card.
 */
import { Thumbnail } from './article.model';

export interface ArchiveEntry {
  id: string;
  /** YYYY-MM-DD folder the article came from. */
  date: string;
  title: string;
  category: string;
  excerpt: string;
  /** e.g. "/posts/2026-06-13/claude-agent-sdk-launch" */
  permalink: string;
  published_at: string;
  reading_time_min?: number | null;
  tags: string[];
  thumbnail?: Thumbnail;
  image?: string;
}

export interface ArchiveIndex {
  version: string;
  generated_at: string;
  count: number;
  articles: ArchiveEntry[];
}
